import { create } from 'zustand';

export type Language = 'vi' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem('wanderlab-lang') as Language) || 'vi',
  setLanguage: (lang) => {
    localStorage.setItem('wanderlab-lang', lang);
    set({ language: lang });
  },
  t: (key, section) => {
    const lang = get().language;
    // Core translation dictionary for the entire website
    const translations: Record<Language, Record<string, any>> = {
      vi: {
        common: {
          home: "Trang Chủ",
          explore: "Khám Phá",
          friends: "Bạn Bè",
          createDiary: "Tạo Nhật Ký",
          createItinerary: "Tạo Lịch Trình",
          selectPlan: "Chọn Gói",
          dashboard: "Trang Cá Nhân",
          admin: "Quản Trị Viên",
          login: "Đăng Nhập",
          register: "Đăng Ký",
          logout: "Đăng Xuất",
          language: "Ngôn ngữ",
          loading: "Đang tải...",
          cancel: "Hủy",
          save: "Lưu thay đổi",
          shareMemory: "Chia sẻ kỷ niệm du lịch của bạn...",
          create: "Tạo",
          recentActivity: "Hoạt Động Gần Đây",
          totalLikes: "Tổng lượt thích",
          comments: "Bình luận",
          bookmarks: "Lượt lưu",
          quickActions: "Hành Động Nhanh",
          createJournal: "📝 Tạo Nhật Ký Mới",
          aiPlanner: "🗺️ Lập Kế Hoạch AI",
          searchExplore: "🔍 Khám Phá",
          edit: "Chỉnh sửa",
          changeCover: "Đổi ảnh bìa",
          location: "Địa điểm",
          travelStats: "Thống Kê Du Lịch",
          savedJournals: "Nhật Ký Đã Lưu",
          savedItineraries: "Lịch Trình Đã Lưu",
          myJournals: "Nhật Ký",
          itineraryStats: "Thống Kê",
          followInfo: "người theo dõi",
          followingInfo: "đang theo dõi",
          diariesInfo: "nhật ký",
          editProfile: "Chỉnh Sửa Trang Cá Nhân",
          fullNameLabel: "Họ và tên",
          locationLabel: "Địa điểm",
          bioLabel: "Tiểu sử (Bio)",
          placeholderName: "Nhập họ và tên...",
          placeholderLocation: "Ví dụ: Hà Nội, Việt Nam",
          placeholderBio: "Giới thiệu ngắn về bản thân...",
        },
        landing: {
          heroTitle: "Ghi lại hành trình,",
          heroHighlight: "Chia sẻ trải nghiệm",
          heroSubtitle: "WanderLab là nền tảng nhật ký du lịch xác thực, nơi bạn khám phá trải nghiệm thật từ cộng đồng du lịch Việt Nam.",
          startFree: "Bắt Đầu Miễn Phí",
          exploreBtn: "Khám Phá",
          whyWanderLab: "Tại sao chọn WanderLab?",
          whySubtitle: "Nền tảng nhật ký du lịch đầu tiên tại Việt Nam với xác thực độ tin cậy",
          feat1Title: "Nhật Ký Xác Thực",
          feat1Desc: "Mọi nhật ký được xác minh bởi cộng đồng, đảm bảo trải nghiệm thực tế và đáng tin cậy.",
          feat2Title: "Khám Phá Việt Nam",
          feat2Desc: "Hàng ngàn điểm đến từ 63 tỉnh thành với ngân sách và lịch trình chi tiết.",
          feat3Title: "AI Lập Kế Hoạch",
          feat3Desc: "Trợ lý AI thông minh giúp bạn lập kế hoạch chuyến đi hoàn hảo trong vài phút.",
          readyToExplore: "Sẵn sàng khám phá?",
          readySubtitle: "Tham gia cộng đồng hàng nghìn du khách Việt Nam đang chia sẻ trải nghiệm mỗi ngày.",
          createAccountFree: "Tạo Tài Khoản Miễn Phí",
          createStory: "Tạo tin",
          trendingDestinations: "Điểm Đến Nổi Bật",
          suggestedTravelers: "Du Khách Nổi Bật",
          seeMoreTravelers: "Xem thêm du khách →",
          feedTitle: "Nhật Ký Du Lịch",
          feedSubtitle: "Khám phá trải nghiệm thật từ cộng đồng",
          loadMoreFriends: "Kết Nối Với Bạn Bè",
          loadingDiaries: "Đang tải nhật ký...",
          noDiaries: "Chưa có nhật ký nào được chia sẻ.",
        },
        explore: {
          title: "Khám Phá Nhật Ký Du Lịch",
          subtitle: "Khám phá trải nghiệm thực tế từ du khách Việt Nam đã được xác minh",
          searchPlaceholder: "Tìm kiếm điểm đến, tỉnh thành hoặc trải nghiệm...",
          filters: "Bộ Lọc",
          activeFilters: "đang dùng",
          clearAll: "Xóa tất cả",
          advancedFilters: "Bộ Lọc Nâng Cao",
          interests: "Sở Thích",
          styles: "Kiểu Du Lịch",
          budget: "Ngân Sách",
          duration: "Thời Gian",
          from: "Từ",
          to: "Đến",
          under15tr: "Dưới 15tr",
          over25tr: "Trên 25tr",
          all: "Tất cả",
          gridView: "Dạng lưới",
          mapView: "Dạng bản đồ",
          mapPlaceholderTitle: "Chế Độ Bản Đồ",
          mapPlaceholderDesc: "Bản đồ tương tác sẽ ra mắt sớm! Chuyển sang chế độ lưới để xem nhật ký.",
          noResults: "Không tìm thấy nhật ký",
          noResultsDesc: "Thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn",
          clearAllFilters: "Xóa Tất Cả Bộ Lọc",
          showingDiaries: "Hiển thị",
          journalsUnit: "nhật ký",
          by: "bởi",
        },
        auth: {
          signIn: "Đăng Nhập",
          signUp: "Đăng Ký",
          email: "Địa chỉ Email",
          password: "Mật khẩu",
          forgotPassword: "Quên mật khẩu?",
          dontHaveAccount: "Chưa có tài khoản?",
          haveAccount: "Đã có tài khoản?",
          fullName: "Họ và tên",
          confirmPassword: "Xác nhận mật khẩu",
        },
        createDiary: {
          title: "Tạo Nhật Ký Chuyến Đi Mới",
          step1: "Thông Tin Cơ Bản",
          step2: "Lịch Trình",
          step3: "Mẹo & Lưu Ý",
          step4: "Ảnh Chuyến Đi",
          step5: "Quyền Riêng Tư",
          next: "Tiếp theo",
          prev: "Quay lại",
          finish: "Hoàn thành & Chia sẻ",
          locationLabel: "Địa điểm chính",
          locationPlaceholder: "Ví dụ: Phú Quốc",
          budgetLabel: "Tổng chi phí dự kiến",
          budgetPlaceholder: "Ví dụ: 10.000.000₫",
          privacyPublic: "Công khai",
          privacyPublicDesc: "Tất cả mọi người đều có thể xem nhật ký này",
          privacyFriends: "Bạn bè",
          privacyFriendsDesc: "Chỉ những người theo dõi bạn mới có thể xem",
          privacyPrivate: "Riêng tư",
          privacyPrivateDesc: "Chỉ mình bạn có thể xem nhật ký này",
        },
        createItinerary: {
          title: "AI Lập Kế Hoạch",
          subtitle: "Tạo Lịch Trình Cá Nhân Hóa",
          desc: "Trả lời 3 câu hỏi ngắn – AI sẽ tạo lịch trình hoàn hảo riêng cho bạn",
          step1: "Điểm đến",
          step2: "Nhóm & Ngân sách",
          step3: "Sở thích",
          step4: "Lịch trình",
          selectDestDesc: "Chọn điểm đến mơ ước của bạn",
          tripDuration: "Thời gian chuyến đi",
          question1: "Bạn muốn đi đâu?",
          question2: "Bạn đi cùng ai?",
          question3: "Mức ngân sách của bạn?",
          question4: "Bạn thích hoạt động gì nhất?",
          optimizeDesc: "Giúp AI tối ưu lịch trình cho bạn",
          activitiesDesc: "Chọn những hoạt động yêu thích (có thể chọn nhiều)",
          itinerarySummary: "Tóm tắt lịch trình",
          dailyItinerary: "Lịch trình từng ngày",
          costEstimate: "Ước tính chi phí",
          totalEstimate: "Tổng ước tính",
          communityJournals: "Nhật ký thực tế từ cộng đồng",
          viewMoreJournals: "Xem thêm nhật ký tại Khám phá",
          share: "Chia sẻ",
          viewSavedDashboard: "Xem lịch trình đã lưu trong Dashboard",
          dayLabel: "Ngày",
          fitLabel: "Phù hợp",
          trustScoreLabel: "Tin cậy",
          backBtn: "Quay lại",
          nextBtn: "Tiếp theo",
          generateBtn: "Tạo Lịch Trình",
          generating: "AI đang tạo lịch trình...",
          resultTitle: "Lịch trình được tạo bởi AI",
          saveItinerary: "Lưu lịch trình",
          saved: "Đã lưu!",
          regenerate: "Tạo lại",
        },
        diaryDetail: {
          trustScore: "Độ Tin Cậy",
          verified: "Đã Xác Minh",
          travelerPhotos: "Ảnh Từ Du Khách",
          photosDesc: "ảnh xác thực • Bấm để xem toàn màn hình",
          saveToPlan: "Lưu Vào Kế Hoạch",
          savedToPlan: "Đã Lưu",
          copyItinerary: "Sao Chép Lịch Trình",
          share: "Chia Sẻ",
          aboutTrip: "Về Chuyến Đi Này",
          dailyItinerary: "Lịch Trình Từng Ngày",
          budgetDetail: "Chi Tiết Ngân Sách",
          tipsExperience: "Mẹo Kinh Nghiệm",
          budgetNotes: "💡 Lưu Ý Ngân Sách",
          budgetPct: "% tổng ngân sách",
          interactiveMap: "📍 Bản Đồ Tương Tác",
          mapComingSoon: "Bản đồ lộ trình tương tác sẽ sớm ra mắt",
          communityReviews: "Đánh Giá Cộng Đồng",
          reviewsUnit: "đánh giá",
          commentsUnit: "bình luận",
          commentsTitle: "Bình Luận",
          creator: "Nhà Sáng Tạo Du Lịch",
          follow: "Theo Dõi",
          tripInfo: "Thông Tin Chuyến Đi",
          similarTrips: "Chuyến Đi Tương Tự",
          viewAllDiaries: "Xem Tất Cả Nhật Ký →",
        },
        partner: {
          badge: "Dành Cho Doanh Nghiệp Du Lịch",
          title: "Chọn Gói Của Bạn",
          subtitle: "Tham gia mạng lưới đã xác minh của WanderLab và tiếp cận 50.000+ du khách đang hoạt động lên kế hoạch chuyến phiêu lưu tiếp theo.",
          viewPricingBtn: "Xem Giá",
          bookDemoBtn: "Đặt Lịch Demo",
          partnerCount: "Doanh Nghiệp Đối Tác",
          activeTravelers: "Du Khách Hoạt Động",
          avgRoi: "Tăng ROI Trung Bình",
          growthAnalytics: "Phân Tích Tăng Trưởng",
          growthAnalyticsDesc: "Theo dõi hiệu suất với thông tin chi tiết thời gian thực",
          trustBadge: "Huy Hiệu Tin Cậy",
          trustBadgeDesc: "Trạng thái đối tác đã xác minh xây dựng uy tín",
          qualityCustomers: "Khách Hàng Chất Lượng",
          qualityCustomersDesc: "Kết nối với du khách sẵn sàng đặt chỗ",
          globalReach: "Tiếp Cận Toàn Cầu",
          globalReachDesc: "Truy cập thị trường quốc tế dễ dàng",
          whyPartnerTitle: "Tại Sao Hợp Tác Với WanderLab?",
          whyPartnerSubtitle: "Mọi thứ bạn cần để phát triển doanh nghiệp du lịch",
          benefit1Title: "50.000+ Du Khách Đang Hoạt Động",
          benefit1Desc: "Kết nối với cộng đồng du khách được xác minh đang tích cực lên kế hoạch chuyến đi",
          benefit2Title: "Tiếp Cận Mục Tiêu",
          benefit2Desc: "Được khám phá bởi du khách quan tâm cụ thể đến điểm đến và dịch vụ của bạn",
          benefit3Title: "ROI Trung Bình 250%",
          benefit3Desc: "Đối tác của chúng tôi thấy tăng trưởng đáng kể về đặt chỗ và hiển thị thương hiệu",
          benefit4Title: "Tin Tưởng & Xác Minh",
          benefit4Desc: "Hưởng lợi từ hệ thống xác minh xây dựng niềm tin của du khách",
          benefit5Title: "Phân Tích Thời Gian Thực",
          benefit5Desc: "Theo dõi hiển thị, nhấp chuột và chuyển đổi với thông tin chi tiết",
          benefit6Title: "Tích Hợp Dễ Dàng",
          benefit6Desc: "Thiết lập liền mạch với hệ thống đặt chỗ và trang web hiện có",
          pricingTitle: "Giá Cả Đơn Giản, Minh Bạch",
          pricingSubtitle: "Chọn gói phù hợp với nhu cầu doanh nghiệp của bạn",
          mostPopular: "Phổ Biến Nhất",
          currentPlan: "Đang Sử Dụng",
          upgrade: "Nâng Cấp",
          planFreeDesc: "Bản miễn phí - Đang sử dụng",
          planStarterDesc: "Phù hợp cho người dùng thường xuyên",
          planProfessionalDesc: "Dành cho người sáng tạo nội dung chuyên nghiệp",
          featureFree1: "AI trợ lý: 5-10 lượt/ngày",
          featureFree2: "Đăng tải nội dung Full HD",
          featureFree3: "Giới hạn dung lượng video",
          featureFree4: "Tạo nhật ký du lịch",
          featureFree5: "Chia sẻ với cộng đồng",
          featureStarter1: "AI trợ lý: 100 lượt/tháng",
          featureStarter2: "Chất lượng video 2K",
          featureStarter3: "Video không giới hạn dung lượng",
          featureStarter4: "Phân tích cơ bản",
          featureStarter5: "Hỗ trợ qua email",
          featureStarter6: "Lưu trữ không giới hạn",
          featureProfessional1: "AI trợ lý: Không giới hạn",
          featureProfessional2: "Nội dung 4K siêu nét",
          featureProfessional3: "Không giới hạn dung lượng",
          featureProfessional4: "Cá nhân hóa trang cá nhân",
          featureProfessional5: "Phân tích & thông tin nâng cao",
          featureProfessional6: "Hỗ trợ ưu tiên 24/7",
          featureProfessional7: "Huy hiệu xác minh",
          featureProfessional8: "Truy cập API",
          trustedTitle: "Được Tin Tưởng Bởi Các Doanh Nghiệp Hàng Đầu",
          trustedSubtitle: "Xem đối tác của chúng tôi nói gì",
          testimonial1Role: "Chủ Sở Hữu",
          testimonial1Text: "WanderLab đã biến đổi doanh nghiệp của chúng tôi. Chúng tôi đã thấy tăng 300% đặt phòng từ du khách quốc tế.",
          testimonial2Role: "Giám Đốc Marketing",
          testimonial2Text: "Chất lượng khách hàng tiềm năng rất xuất sắc. Đây là những du khách thực sự quan tâm và sẵn sàng đặt chỗ.",
          testimonial3Role: "Người Sáng Lập",
          testimonial3Text: "Bảng điều khiển phân tích cung cấp thông tin chi tiết mà chúng tôi chưa từng có. Giờ đây chúng tôi có thể tối ưu hóa dịch vụ dựa trên dữ liệu thực.",
          readyTitle: "Sẵn Sàng Bắt Đầu?",
          readySubtitle: "Điền form và chúng tôi sẽ liên hệ trong vòng 24 giờ",
          labelBusinessName: "Tên Doanh Nghiệp *",
          labelContactName: "Tên Liên Hệ *",
          labelEmail: "Địa Chỉ Email *",
          labelPhone: "Số Điện Thoại",
          labelBusinessType: "Loại Hình Doanh Nghiệp *",
          selectTypePlaceholder: "Chọn loại hình",
          typeHotel: "Khách Sạn / Resort",
          typeTour: "Công Ty Lữ Hành",
          typeActivity: "Nhà Cung Cấp Hoạt Động",
          typeRestaurant: "Nhà Hàng",
          typeTransport: "Vận Chuyển",
          typeOther: "Khác",
          labelLocation: "Địa Điểm *",
          placeholderLocation: "Thành phố, Việt Nam",
          labelWebsite: "Website",
          labelIntro: "Giới thiệu về doanh nghiệp của bạn",
          placeholderIntro: "Doanh nghiệp bạn cung cấp dịch vụ gì? Mục tiêu của bạn với WanderLab là gì?",
          submitBtn: "Gửi Đơn Đăng Ký",
          termsAgreement: "Bằng cách gửi, bạn đồng ý với Điều Khoản Dịch Vụ và Chính Sách Bảo Mật của chúng tôi",
          termsLink: "Điều Khoản Dịch Vụ",
          privacyLink: "Chính Sách Bảo Mật",
          submitSuccess: "Cảm ơn bạn đã quan tâm! Chúng tôi sẽ liên hệ trong vòng 24 giờ."
        },
        settings: {
          title: "Cài Đặt",
          subtitle: "Quản lý tài khoản và tùy chỉnh ứng dụng",
          dangerZone: "Vùng Nguy Hiểm",
          logout: "Đăng xuất",
          deleteAccount: "Xóa tài khoản",
          featureDev: "Tính năng đang phát triển!",
          defaultUser: "Người dùng",
          noEmail: "Chưa cập nhật email",
          noPhone: "Chưa cập nhật số điện thoại",
          noAddress: "Chưa cập nhật địa chỉ",
          secAccount: "Tài khoản",
          secPrivacy: "Quyền riêng tư & Bảo mật",
          secNotifications: "Thông báo",
          secAppearance: "Giao diện",
          secAbout: "Về ứng dụng",
          itemPersonalInfo: "Thông tin cá nhân",
          itemContact: "Email & Số điện thoại",
          itemAddress: "Địa chỉ",
          itemPassword: "Đổi mật khẩu",
          itemPrivacy: "Quyền riêng tư",
          itemSecurity: "Bảo mật",
          itemProfileVisibility: "Ai có thể xem hồ sơ",
          itemPushNav: "Thông báo đẩy",
          itemEmailNav: "Thông báo Email",
          itemSound: "Âm thanh",
          itemDarkMode: "Chế độ tối",
          itemLanguage: "Ngôn ngữ",
          itemTerms: "Điều khoản sử dụng",
          itemPolicy: "Chính sách bảo mật",
          itemVersion: "Phiên bản",
          // Profile modal
          profileModalTitle: "Thông tin cá nhân",
          profileModalSubtitle: "Cập nhật thông tin cá nhân của bạn",
          fullNameLabel: "Họ và tên",
          fullNamePlaceholder: "Nhập họ và tên...",
          bioLabel: "Tiểu sử",
          bioPlaceholder: "Giới thiệu ngắn về bản thân...",
          locationLabel: "Địa điểm",
          locationPlaceholder: "Ví dụ: Hà Nội, Việt Nam",
          saveBtn: "Lưu thay đổi",
          cancelBtn: "Hủy",
          saving: "Đang lưu...",
          profileUpdateSuccess: "Cập nhật thông tin thành công!",
          profileUpdateError: "Không thể cập nhật thông tin. Vui lòng thử lại.",
          // Contact modal
          contactModalTitle: "Email & Số điện thoại",
          contactModalSubtitle: "Quản lý thông tin liên hệ",
          emailLabel: "Địa chỉ Email",
          emailPlaceholder: "example@email.com",
          phoneLabel: "Số điện thoại",
          phonePlaceholder: "0912 345 678",
          emailUpdateSuccess: "Đã gửi email xác nhận đến địa chỉ mới!",
          phoneUpdateSuccess: "Cập nhật số điện thoại thành công!",
          contactUpdateError: "Không thể cập nhật. Vui lòng thử lại.",
          emailConfirmNote: "Bạn sẽ nhận được email xác nhận tại địa chỉ mới",
          // Password modal
          passwordModalTitle: "Đổi mật khẩu",
          passwordModalSubtitle: "Đảm bảo tài khoản luôn an toàn",
          currentPassword: "Mật khẩu hiện tại",
          currentPasswordPlaceholder: "Nhập mật khẩu hiện tại...",
          newPassword: "Mật khẩu mới",
          newPasswordPlaceholder: "Nhập mật khẩu mới...",
          confirmPassword: "Xác nhận mật khẩu mới",
          confirmPasswordPlaceholder: "Nhập lại mật khẩu mới...",
          passwordChangeSuccess: "Đổi mật khẩu thành công!",
          passwordChangeError: "Không thể đổi mật khẩu. Vui lòng thử lại.",
          passwordMismatch: "Mật khẩu xác nhận không khớp",
          passwordTooShort: "Mật khẩu phải có ít nhất 6 ký tự",
          passwordRequirements: "Mật khẩu phải có ít nhất 6 ký tự",
          changePasswordBtn: "Đổi mật khẩu",
          changingPassword: "Đang đổi..."
        }
      },
      en: {
        common: {
          home: "Home",
          explore: "Explore",
          friends: "Friends",
          createDiary: "Create Journal",
          createItinerary: "AI Itinerary",
          selectPlan: "Pricing Plans",
          dashboard: "Profile",
          admin: "Admin Panel",
          login: "Log In",
          register: "Sign Up",
          logout: "Log Out",
          language: "Language",
          loading: "Loading...",
          cancel: "Cancel",
          save: "Save Changes",
          shareMemory: "Share your travel memories...",
          create: "Create",
          recentActivity: "Recent Activity",
          totalLikes: "Total likes",
          comments: "Comments",
          bookmarks: "Saved posts",
          quickActions: "Quick Actions",
          createJournal: "📝 Create New Journal",
          aiPlanner: "🗺️ AI Plan Itinerary",
          searchExplore: "🔍 Search & Explore",
          edit: "Edit Profile",
          changeCover: "Change cover image",
          location: "Location",
          travelStats: "Travel Stats",
          savedJournals: "Saved Journals",
          savedItineraries: "Saved Itineraries",
          myJournals: "My Journals",
          itineraryStats: "Statistics",
          followInfo: "Followers",
          followingInfo: "Following",
          diariesInfo: "Journals",
          editProfile: "Edit Personal Profile",
          fullNameLabel: "Full Name",
          locationLabel: "Location",
          bioLabel: "Bio description",
          placeholderName: "Enter full name...",
          placeholderLocation: "E.g. Hanoi, Vietnam",
          placeholderBio: "Write a short bio about yourself...",
        },
        landing: {
          heroTitle: "Record Journeys,",
          heroHighlight: "Share Experiences",
          heroSubtitle: "WanderLab is an authentic travel journal platform where you discover real experiences from the Vietnamese travel community.",
          startFree: "Start For Free",
          exploreBtn: "Explore Now",
          whyWanderLab: "Why WanderLab?",
          whySubtitle: "Vietnam's first travel journal platform with reliability verification",
          feat1Title: "Verified Journals",
          feat1Desc: "Every journal is verified by the community, ensuring realistic and trustworthy experiences.",
          feat2Title: "Explore Vietnam",
          feat2Desc: "Thousands of destinations from 63 provinces with detailed budgets and itineraries.",
          feat3Title: "AI Trip Planner",
          feat3Desc: "Smart AI assistant helps you plan the perfect trip in minutes.",
          readyToExplore: "Ready to explore?",
          readySubtitle: "Join a community of thousands of Vietnamese travelers sharing experiences daily.",
          createAccountFree: "Create Free Account",
          createStory: "Add story",
          trendingDestinations: "Trending Destinations",
          suggestedTravelers: "Featured Travelers",
          seeMoreTravelers: "View more travelers →",
          feedTitle: "Travel Journals",
          feedSubtitle: "Discover authentic experiences from the community",
          loadMoreFriends: "Connect With Friends",
          loadingDiaries: "Loading journals...",
          noDiaries: "No journals have been shared yet.",
        },
        explore: {
          title: "Explore Travel Journals",
          subtitle: "Discover authentic experiences from verified Vietnamese travelers",
          searchPlaceholder: "Search for destinations, provinces or experiences...",
          filters: "Filters",
          activeFilters: "active",
          clearAll: "Clear all",
          advancedFilters: "Advanced Filters",
          interests: "Interests",
          styles: "Travel Style",
          budget: "Budget Limit",
          duration: "Duration",
          from: "From",
          to: "To",
          under15tr: "Under 15m",
          over25tr: "Over 25m",
          all: "All",
          gridView: "Grid layout",
          mapView: "Map layout",
          mapPlaceholderTitle: "Map View Mode",
          mapPlaceholderDesc: "Interactive map coming soon! Switch to grid layout to view travel journals.",
          noResults: "No journals found",
          noResultsDesc: "Try adjusting your search query or filters",
          clearAllFilters: "Clear All Filters",
          showingDiaries: "Showing",
          journalsUnit: "journals",
          by: "by",
        },
        auth: {
          signIn: "Log In",
          signUp: "Sign Up",
          email: "Email Address",
          password: "Password",
          forgotPassword: "Forgot password?",
          dontHaveAccount: "Don't have an account?",
          haveAccount: "Already have an account?",
          fullName: "Full Name",
          confirmPassword: "Confirm Password",
        },
        createDiary: {
          title: "Create New Travel Journal",
          step1: "Basic Information",
          step2: "Daily Itinerary",
          step3: "Tips & Notes",
          step4: "Travel Photos",
          step5: "Privacy Settings",
          next: "Next",
          prev: "Back",
          finish: "Finish & Share",
          locationLabel: "Primary Destination",
          locationPlaceholder: "E.g. Phu Quoc",
          budgetLabel: "Estimated Total Cost",
          budgetPlaceholder: "E.g. 10,000,000₫",
          privacyPublic: "Public",
          privacyPublicDesc: "Anyone can view this travel journal",
          privacyFriends: "Friends Only",
          privacyFriendsDesc: "Only your followers can view",
          privacyPrivate: "Private",
          privacyPrivateDesc: "Only you can view this journal",
        },
        createItinerary: {
          title: "AI Trip Planner",
          subtitle: "Generate Personalized Itinerary",
          desc: "Answer 3 short questions – AI will create a perfect itinerary just for you",
          step1: "Destination",
          step2: "Group & Budget",
          step3: "Interests",
          step4: "Itinerary",
          selectDestDesc: "Select your dream destination",
          tripDuration: "Trip duration",
          question1: "Where do you want to go?",
          question2: "Who are you traveling with?",
          question3: "What is your budget?",
          question4: "What activities do you like most?",
          optimizeDesc: "Help AI optimize your itinerary",
          activitiesDesc: "Choose your favorite activities (multiple choice)",
          itinerarySummary: "Itinerary Summary",
          dailyItinerary: "Daily Itinerary",
          costEstimate: "Estimated Cost",
          totalEstimate: "Total estimate",
          communityJournals: "Real travel journals from the community",
          viewMoreJournals: "View more journals in Explore",
          share: "Share",
          viewSavedDashboard: "View saved itineraries in Dashboard",
          dayLabel: "Day",
          fitLabel: "Fit",
          trustScoreLabel: "Trust",
          backBtn: "Back",
          nextBtn: "Next",
          generateBtn: "Generate Itinerary",
          generating: "AI is creating itinerary...",
          resultTitle: "AI Generated Itinerary",
          saveItinerary: "Save Itinerary",
          saved: "Saved!",
          regenerate: "Regenerate",
        },
        diaryDetail: {
          trustScore: "Trust Score",
          verified: "Verified",
          travelerPhotos: "Traveler Photos",
          photosDesc: "authentic photos • Click to view full screen",
          saveToPlan: "Save to Plan",
          savedToPlan: "Saved",
          copyItinerary: "Copy Itinerary",
          share: "Share",
          aboutTrip: "About This Trip",
          dailyItinerary: "Daily Itinerary",
          budgetDetail: "Budget Details",
          tipsExperience: "Tips & Experience",
          budgetNotes: "💡 Budget Notes",
          budgetPct: "% of total budget",
          interactiveMap: "📍 Interactive Map",
          mapComingSoon: "Interactive route map coming soon",
          communityReviews: "Community Reviews",
          reviewsUnit: "reviews",
          commentsUnit: "comments",
          commentsTitle: "Comments",
          creator: "Travel Creator",
          follow: "Follow",
          tripInfo: "Trip Information",
          similarTrips: "Similar Trips",
          viewAllDiaries: "View All Journals →",
        },
        partner: {
          badge: "For Travel Businesses",
          title: "Choose Your Plan",
          subtitle: "Join WanderLab's verified network and reach 50,000+ active travelers planning their next adventure.",
          viewPricingBtn: "See Pricing",
          bookDemoBtn: "Book a Demo",
          partnerCount: "Partner Businesses",
          activeTravelers: "Active Travelers",
          avgRoi: "Average ROI Increase",
          growthAnalytics: "Growth Analytics",
          growthAnalyticsDesc: "Track performance with real-time insights",
          trustBadge: "Trust Badge",
          trustBadgeDesc: "Verified partner status builds credibility",
          qualityCustomers: "Quality Customers",
          qualityCustomersDesc: "Connect with travelers ready to book",
          globalReach: "Global Reach",
          globalReachDesc: "Access international markets easily",
          whyPartnerTitle: "Why Partner with WanderLab?",
          whyPartnerSubtitle: "Everything you need to grow your travel business",
          benefit1Title: "50,000+ Active Travelers",
          benefit1Desc: "Connect with a verified community of travelers actively planning trips",
          benefit2Title: "Targeted Reach",
          benefit2Desc: "Get discovered by travelers specifically interested in your destinations and services",
          benefit3Title: "250% Average ROI",
          benefit3Desc: "Our partners see significant growth in bookings and brand visibility",
          benefit4Title: "Trust & Verification",
          benefit4Desc: "Benefit from a verification system that builds trust with travelers",
          benefit5Title: "Real-Time Analytics",
          benefit5Desc: "Track impressions, clicks, and conversions with detailed insights",
          benefit6Title: "Easy Integration",
          benefit6Desc: "Set up seamlessly with your existing booking systems and website",
          pricingTitle: "Simple, Transparent Pricing",
          pricingSubtitle: "Choose the plan that fits your business needs",
          mostPopular: "Most Popular",
          currentPlan: "Current Plan",
          upgrade: "Upgrade",
          planFreeDesc: "Free plan - Currently in use",
          planStarterDesc: "Best for regular users",
          planProfessionalDesc: "For professional content creators",
          featureFree1: "AI Assistant: 5-10 requests/day",
          featureFree2: "Upload Full HD content",
          featureFree3: "Limited video size",
          featureFree4: "Create travel journals",
          featureFree5: "Share with community",
          featureStarter1: "AI Assistant: 100 requests/month",
          featureStarter2: "2K video quality",
          featureStarter3: "Unlimited video size",
          featureStarter4: "Basic analytics",
          featureStarter5: "Email support",
          featureStarter6: "Unlimited storage",
          featureProfessional1: "AI Assistant: Unlimited",
          featureProfessional2: "Ultra-sharp 4K content",
          featureProfessional3: "Unlimited storage size",
          featureProfessional4: "Profile personalization",
          featureProfessional5: "Advanced analytics & insights",
          featureProfessional6: "24/7 priority support",
          featureProfessional7: "Verification badge",
          featureProfessional8: "API access",
          trustedTitle: "Trusted by Leading Businesses",
          trustedSubtitle: "See what our partners say",
          testimonial1Role: "Owner",
          testimonial1Text: "WanderLab has transformed our business. We saw a 300% increase in bookings from international travelers.",
          testimonial2Role: "Marketing Director",
          testimonial2Text: "The quality of leads is excellent. These are real travelers who are interested and ready to book.",
          testimonial3Role: "Founder",
          testimonial3Text: "The analytics dashboard provides insights we never had before. We can now optimize our services based on real data.",
          readyTitle: "Ready to Get Started?",
          readySubtitle: "Fill out the form and we will contact you within 24 hours",
          labelBusinessName: "Business Name *",
          labelContactName: "Contact Name *",
          labelEmail: "Email Address *",
          labelPhone: "Phone Number",
          labelBusinessType: "Business Type *",
          selectTypePlaceholder: "Select business type",
          typeHotel: "Hotel / Resort",
          typeTour: "Tour Operator",
          typeActivity: "Activity Provider",
          typeRestaurant: "Restaurant",
          typeTransport: "Transportation",
          typeOther: "Other",
          labelLocation: "Location *",
          placeholderLocation: "City, Vietnam",
          labelWebsite: "Website",
          labelIntro: "About your business",
          placeholderIntro: "What services does your business provide? What are your goals with WanderLab?",
          submitBtn: "Submit Application",
          termsAgreement: "By submitting, you agree to our Terms of Service and Privacy Policy",
          termsLink: "Terms of Service",
          privacyLink: "Privacy Policy",
          submitSuccess: "Thank you for your interest! We will contact you within 24 hours."
        },
        settings: {
          title: "Settings",
          subtitle: "Manage your account and customize the application",
          dangerZone: "Danger Zone",
          logout: "Log Out",
          deleteAccount: "Delete Account",
          featureDev: "Feature is under development!",
          defaultUser: "User",
          noEmail: "Email not updated",
          noPhone: "Phone not updated",
          noAddress: "Address not updated",
          secAccount: "Account",
          secPrivacy: "Privacy & Security",
          secNotifications: "Notifications",
          secAppearance: "Appearance",
          secAbout: "About App",
          itemPersonalInfo: "Personal Information",
          itemContact: "Email & Phone Number",
          itemAddress: "Address",
          itemPassword: "Change Password",
          itemPrivacy: "Privacy",
          itemSecurity: "Security",
          itemProfileVisibility: "Who can see profile",
          itemPushNav: "Push Notifications",
          itemEmailNav: "Email Notifications",
          itemSound: "Sound",
          itemDarkMode: "Dark Mode",
          itemLanguage: "Language",
          itemTerms: "Terms of Service",
          itemPolicy: "Privacy Policy",
          itemVersion: "Version",
          // Profile modal
          profileModalTitle: "Personal Information",
          profileModalSubtitle: "Update your personal information",
          fullNameLabel: "Full Name",
          fullNamePlaceholder: "Enter full name...",
          bioLabel: "Bio",
          bioPlaceholder: "Tell us about yourself...",
          locationLabel: "Location",
          locationPlaceholder: "e.g., Hanoi, Vietnam",
          saveBtn: "Save Changes",
          cancelBtn: "Cancel",
          saving: "Saving...",
          profileUpdateSuccess: "Profile updated successfully!",
          profileUpdateError: "Failed to update profile. Please try again.",
          // Contact modal
          contactModalTitle: "Email & Phone Number",
          contactModalSubtitle: "Manage your contact information",
          emailLabel: "Email Address",
          emailPlaceholder: "example@email.com",
          phoneLabel: "Phone Number",
          phonePlaceholder: "+84 912 345 678",
          emailUpdateSuccess: "Confirmation email sent to the new address!",
          phoneUpdateSuccess: "Phone number updated successfully!",
          contactUpdateError: "Failed to update. Please try again.",
          emailConfirmNote: "You will receive a confirmation email at the new address",
          // Password modal
          passwordModalTitle: "Change Password",
          passwordModalSubtitle: "Keep your account secure",
          currentPassword: "Current Password",
          currentPasswordPlaceholder: "Enter current password...",
          newPassword: "New Password",
          newPasswordPlaceholder: "Enter new password...",
          confirmPassword: "Confirm New Password",
          confirmPasswordPlaceholder: "Re-enter new password...",
          passwordChangeSuccess: "Password changed successfully!",
          passwordChangeError: "Failed to change password. Please try again.",
          passwordMismatch: "Passwords do not match",
          passwordTooShort: "Password must be at least 6 characters",
          passwordRequirements: "Password must be at least 6 characters",
          changePasswordBtn: "Change Password",
          changingPassword: "Changing..."
        }
      }
    };

    if (section) {
      return translations[lang]?.[section]?.[key] || translations['vi']?.[section]?.[key] || key;
    }
    return translations[lang]?.common?.[key] || translations['vi']?.common?.[key] || key;
  }
}));
