import { create } from 'zustand';

export type Language = 'vi' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem('wanderlab-lang') as Language) || 'vi',
  setLanguage: (lang) => {
    localStorage.setItem('wanderlab-lang', lang);
    set({ language: lang });
  },
  t: (key, section) => {
    const lang = get().language;
    // Core translation dictionary for the entire website
    const translations: Record<Language, Record<string, any>> = {
      vi: {
        common: {
          home: "Trang Chủ",
          explore: "Khám Phá",
          friends: "Bạn Bè",
          createDiary: "Tạo Nhật Ký",
          createItinerary: "Tạo Lịch Trình",
          selectPlan: "Chọn Gói",
          dashboard: "Trang Cá Nhân",
          admin: "Quản Trị Viên",
          login: "Đăng Nhập",
          register: "Đăng Ký",
          logout: "Đăng Xuất",
          language: "Ngôn ngữ",
          loading: "Đang tải...",
          cancel: "Hủy",
          save: "Lưu thay đổi",
          shareMemory: "Chia sẻ kỷ niệm du lịch của bạn...",
          create: "Tạo",
          recentActivity: "Hoạt Động Gần Đây",
          totalLikes: "Tổng lượt thích",
          comments: "Bình luận",
          bookmarks: "Lượt lưu",
          quickActions: "Hành Động Nhanh",
          createJournal: "📝 Tạo Nhật Ký Mới",
          aiPlanner: "🗺️ Lập Kế Hoạch AI",
          searchExplore: "🔍 Khám Phá",
          edit: "Chỉnh sửa",
          changeCover: "Đổi ảnh bìa",
          location: "Địa điểm",
          travelStats: "Thống Kê Du Lịch",
          savedJournals: "Nhật Ký Đã Lưu",
          myJournals: "Nhật Ký",
          itineraryStats: "Thống Kê",
          followInfo: "người theo dõi",
          followingInfo: "đang theo dõi",
          diariesInfo: "nhật ký",
          editProfile: "Chỉnh Sửa Trang Cá Nhân",
          fullNameLabel: "Họ và tên",
          locationLabel: "Địa điểm",
          bioLabel: "Tiểu sử (Bio)",
          placeholderName: "Nhập họ và tên...",
          placeholderLocation: "Ví dụ: Hà Nội, Việt Nam",
          placeholderBio: "Giới thiệu ngắn về bản thân...",
        },
        landing: {
          heroTitle: "Ghi lại hành trình,",
          heroHighlight: "Chia sẻ trải nghiệm",
          heroSubtitle: "WanderLab là nền tảng nhật ký du lịch xác thực, nơi bạn khám phá trải nghiệm thật từ cộng đồng du lịch Việt Nam.",
          startFree: "Bắt Đầu Miễn Phí",
          exploreBtn: "Khám Phá",
          whyWanderLab: "Tại sao chọn WanderLab?",
          whySubtitle: "Nền tảng nhật ký du lịch đầu tiên tại Việt Nam với xác thực độ tin cậy",
          feat1Title: "Nhật Ký Xác Thực",
          feat1Desc: "Mọi nhật ký được xác minh bởi cộng đồng, đảm bảo trải nghiệm thực tế và đáng tin cậy.",
          feat2Title: "Khám Phá Việt Nam",
          feat2Desc: "Hàng ngàn điểm đến từ 63 tỉnh thành với ngân sách và lịch trình chi tiết.",
          feat3Title: "AI Lập Kế Hoạch",
          feat3Desc: "Trợ lý AI thông minh giúp bạn lập kế hoạch chuyến đi hoàn hảo trong vài phút.",
          readyToExplore: "Sẵn sàng khám phá?",
          readySubtitle: "Tham gia cộng đồng hàng nghìn du khách Việt Nam đang chia sẻ trải nghiệm mỗi ngày.",
          createAccountFree: "Tạo Tài Khoản Miễn Phí",
          createStory: "Tạo tin",
          trendingDestinations: "Điểm Đến Nổi Bật",
          suggestedTravelers: "Du Khách Nổi Bật",
          seeMoreTravelers: "Xem thêm du khách →",
          feedTitle: "Nhật Ký Du Lịch",
          feedSubtitle: "Khám phá trải nghiệm thật từ cộng đồng",
          loadMoreFriends: "Kết Nối Với Bạn Bè",
          loadingDiaries: "Đang tải nhật ký...",
          noDiaries: "Chưa có nhật ký nào được chia sẻ.",
        },
        explore: {
          title: "Khám Phá Nhật Ký Du Lịch",
          subtitle: "Khám phá trải nghiệm thực tế từ du khách Việt Nam đã được xác minh",
          searchPlaceholder: "Tìm kiếm điểm đến, tỉnh thành hoặc trải nghiệm...",
          filters: "Bộ Lọc",
          activeFilters: "đang dùng",
          clearAll: "Xóa tất cả",
          advancedFilters: "Bộ Lọc Nâng Cao",
          interests: "Sở Thích",
          styles: "Kiểu Du Lịch",
          budget: "Ngân Sách",
          duration: "Thời Gian",
          from: "Từ",
          to: "Đến",
          under15tr: "Dưới 15tr",
          over25tr: "Trên 25tr",
          all: "Tất cả",
          gridView: "Dạng lưới",
          mapView: "Dạng bản đồ",
          mapPlaceholderTitle: "Chế Độ Bản Đồ",
          mapPlaceholderDesc: "Bản đồ tương tác sẽ ra mắt sớm! Chuyển sang chế độ lưới để xem nhật ký.",
          noResults: "Không tìm thấy nhật ký",
          noResultsDesc: "Thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn",
          clearAllFilters: "Xóa Tất Cả Bộ Lọc",
          showingDiaries: "Hiển thị",
          journalsUnit: "nhật ký",
          by: "bởi",
        },
        auth: {
          signIn: "Đăng Nhập",
          signUp: "Đăng Ký",
          email: "Địa chỉ Email",
          password: "Mật khẩu",
          forgotPassword: "Quên mật khẩu?",
          dontHaveAccount: "Chưa có tài khoản?",
          haveAccount: "Đã có tài khoản?",
          fullName: "Họ và tên",
          confirmPassword: "Xác nhận mật khẩu",
        },
        createDiary: {
          title: "Tạo Nhật Ký Chuyến Đi Mới",
          step1: "Thông Tin Cơ Bản",
          step2: "Lịch Trình",
          step3: "Mẹo & Lưu Ý",
          step4: "Ảnh Chuyến Đi",
          step5: "Quyền Riêng Tư",
          next: "Tiếp theo",
          prev: "Quay lại",
          finish: "Hoàn thành & Chia sẻ",
          locationLabel: "Địa điểm chính",
          locationPlaceholder: "Ví dụ: Phú Quốc",
          budgetLabel: "Tổng chi phí dự kiến",
          budgetPlaceholder: "Ví dụ: 10.000.000₫",
          privacyPublic: "Công khai",
          privacyPublicDesc: "Tất cả mọi người đều có thể xem nhật ký này",
          privacyFriends: "Bạn bè",
          privacyFriendsDesc: "Chỉ những người theo dõi bạn mới có thể xem",
          privacyPrivate: "Riêng tư",
          privacyPrivateDesc: "Chỉ mình bạn có thể xem nhật ký này",
        },
        createItinerary: {
          title: "AI Lập Kế Hoạch",
          subtitle: "Tạo Lịch Trình Cá Nhân Hóa",
          desc: "Trả lời 3 câu hỏi ngắn – AI sẽ tạo lịch trình hoàn hảo riêng cho bạn",
          step1: "Điểm đến",
          step2: "Nhóm & Ngân sách",
          step3: "Sở thích",
          step4: "Lịch trình",
          selectDestDesc: "Chọn điểm đến mơ ước của bạn",
          tripDuration: "Thời gian chuyến đi",
          question1: "Bạn muốn đi đâu?",
          question2: "Bạn đi cùng ai?",
          question3: "Mức ngân sách của bạn?",
          question4: "Bạn thích hoạt động gì nhất?",
          optimizeDesc: "Giúp AI tối ưu lịch trình cho bạn",
          activitiesDesc: "Chọn những hoạt động yêu thích (có thể chọn nhiều)",
          itinerarySummary: "Tóm tắt lịch trình",
          dailyItinerary: "Lịch trình từng ngày",
          costEstimate: "Ước tính chi phí",
          totalEstimate: "Tổng ước tính",
          communityJournals: "Nhật ký thực tế từ cộng đồng",
          viewMoreJournals: "Xem thêm nhật ký tại Khám phá",
          share: "Chia sẻ",
          viewSavedDashboard: "Xem lịch trình đã lưu trong Dashboard",
          dayLabel: "Ngày",
          fitLabel: "Phù hợp",
          trustScoreLabel: "Tin cậy",
          backBtn: "Quay lại",
          nextBtn: "Tiếp theo",
          generateBtn: "Tạo Lịch Trình",
          generating: "AI đang tạo lịch trình...",
          resultTitle: "Lịch trình được tạo bởi AI",
          saveItinerary: "Lưu lịch trình",
          saved: "Đã lưu!",
          regenerate: "Tạo lại",
        },
        diaryDetail: {
          trustScore: "Độ Tin Cậy",
          verified: "Đã Xác Minh",
          travelerPhotos: "Ảnh Từ Du Khách",
          photosDesc: "ảnh xác thực • Bấm để xem toàn màn hình",
          saveToPlan: "Lưu Vào Kế Hoạch",
          savedToPlan: "Đã Lưu",
          copyItinerary: "Sao Chép Lịch Trình",
          share: "Chia Sẻ",
          aboutTrip: "Về Chuyến Đi Này",
          dailyItinerary: "Lịch Trình Từng Ngày",
          budgetDetail: "Chi Tiết Ngân Sách",
          tipsExperience: "Mẹo Kinh Nghiệm",
          budgetNotes: "💡 Lưu Ý Ngân Sách",
          budgetPct: "% tổng ngân sách",
          interactiveMap: "📍 Bản Đồ Tương Tác",
          mapComingSoon: "Bản đồ lộ trình tương tác sẽ sớm ra mắt",
          communityReviews: "Đánh Giá Cộng Đồng",
          reviewsUnit: "đánh giá",
          commentsUnit: "bình luận",
          commentsTitle: "Bình Luận",
          creator: "Nhà Sáng Tạo Du Lịch",
          follow: "Theo Dõi",
          tripInfo: "Thông Tin Chuyến Đi",
          similarTrips: "Chuyến Đi Tương Tự",
          viewAllDiaries: "Xem Tất Cả Nhật Ký →",
        },
        partner: {
          title: "Dành Cho Doanh Nghiệp Du Lịch",
          heroTitle: "Chọn Gói Của Bạn",
          heroDesc: "Tham gia mạng lưới đã xác minh của WanderLab và tiếp cận 50.000+ du khách đang hoạt động lên kế hoạch chuyến phiêu lưu tiếp theo.",
          viewPricing: "Xem Giá",
          bookDemo: "Đặt Lịch Demo",
          statPartners: "Doanh Nghiệp Đối Tác",
          statTravelers: "Du Khách Hoạt Động",
          statROI: "Tăng ROI Trung Bình",
          growthTitle: "Phân Tích Tăng Trưởng",
          growthDesc: "Theo dõi hiệu suất với thông tin chi tiết thời gian thực",
          trustTitle: "Huy Hiệu Tin Cậy",
          trustDesc: "Trạng thái đối tác đã xác minh xây dựng uy tín",
          customersTitle: "Khách Hàng Chất Lượng",
          customersDesc: "Kết nối với du khách sẵn sàng đặt chỗ",
          globalTitle: "Tiếp Cận Toàn Cầu",
          globalDesc: "Truy cập thị trường quốc tế dễ dàng",
          whyTitle: "Tại Sao Hợp Tác Với WanderLab?",
          whyDesc: "Mọi thứ bạn cần để phát triển doanh nghiệp du lịch",
          pricingTitle: "Giá Cả Đơn Giản, Minh Bạch",
          pricingDesc: "Chọn gói phù hợp với nhu cầu doanh nghiệp của bạn",
          popular: "Phổ Biến Nhất",
          currentPlan: "Đang Sử Dụng",
          upgrade: "Nâng Cấp",
          benefit1Title: "50.000+ Du Khách Đang Hoạt Động",
          benefit1Desc: "Kết nối với cộng đồng du khách được xác minh đang tích cực lên kế hoạch chuyến đi",
          benefit2Title: "Tiếp Cận Mục Tiêu",
          benefit2Desc: "Được khám phá bởi du khách quan tâm cụ thể đến điểm đến và dịch vụ của bạn",
          benefit3Title: "ROI Trung Bình 250%",
          benefit3Desc: "Đối tác của chúng tôi thấy tăng trưởng đáng kể về đặt chỗ và hiển thị thương hiệu",
          benefit4Title: "Tin Tưởng & Xác Minh",
          benefit4Desc: "Hưởng lợi từ hệ thống xác minh xây dựng niềm tin của du khách",
          benefit5Title: "Phân Tích Thời Gian Thực",
          benefit5Desc: "Theo dõi hiển thị, nhấp chuột và chuyển đổi với thông tin chi tiết",
          benefit6Title: "Tích Hợp Dễ Dàng",
          benefit6Desc: "Thiết lập liền mạch với hệ thống đặt chỗ và trang web hiện có",
          freeDesc: "Bản miễn phí - Đang sử dụng",
          freeFeat1: "AI trợ lý: 5-10 lượt/ngày",
          freeFeat2: "Đăng tải nội dung Full HD",
          freeFeat3: "Giới hạn dung lượng video",
          freeFeat4: "Tạo nhật ký du lịch",
          freeFeat5: "Chia sẻ với cộng đồng",
          starterDesc: "Phù hợp cho người dùng thường xuyên",
          starterFeat1: "AI trợ lý: 100 lượt/tháng",
          starterFeat2: "Chất lượng video 2K",
          starterFeat3: "Video không giới hạn dung lượng",
          starterFeat4: "Phân tích cơ bản",
          starterFeat5: "Hỗ trợ qua email",
          starterFeat6: "Lưu trữ không giới hạn",
          proDesc: "Dành cho người sáng tạo nội dung chuyên nghiệp",
          proFeat1: "AI trợ lý: Không giới hạn",
          proFeat2: "Nội dung 4K siêu nét",
          proFeat3: "Không giới hạn dung lượng",
          proFeat4: "Cá nhân hóa trang cá nhân",
          proFeat5: "Phân tích & thông tin nâng cao",
          proFeat6: "Hỗ trợ ưu tiên 24/7",
          proFeat7: "Huy hiệu xác minh",
          proFeat8: "Truy cập API",
        },
        friends: {
          title: "Bạn Bè",
          subtitle: "Kết nối và chia sẻ trải nghiệm du lịch",
          searchPlaceholder: "Tìm kiếm bạn bè...",
          requests: "Lời mời kết bạn",
          friendsList: "Bạn bè",
          groups: "Nhóm du lịch",
          mutualFriends: "bạn chung",
          accept: "Chấp nhận",
          decline: "Từ chối",
          message: "Nhắn tin",
          diaries: "nhật ký",
          members: "thành viên",
          posts: "bài viết",
          join: "Tham gia",
          viewMore: "Xem thêm",
        }
      },
      en: {
        common: {
          home: "Home",
          explore: "Explore",
          friends: "Friends",
          createDiary: "Create Journal",
          createItinerary: "AI Itinerary",
          selectPlan: "Pricing Plans",
          dashboard: "Profile",
          admin: "Admin Panel",
          login: "Log In",
          register: "Sign Up",
          logout: "Log Out",
          language: "Language",
          loading: "Loading...",
          cancel: "Cancel",
          save: "Save Changes",
          shareMemory: "Share your travel memories...",
          create: "Create",
          recentActivity: "Recent Activity",
          totalLikes: "Total likes",
          comments: "Comments",
          bookmarks: "Saved posts",
          quickActions: "Quick Actions",
          createJournal: "📝 Create New Journal",
          aiPlanner: "🗺️ AI Plan Itinerary",
          searchExplore: "🔍 Search & Explore",
          edit: "Edit Profile",
          changeCover: "Change cover image",
          location: "Location",
          travelStats: "Travel Stats",
          savedJournals: "Saved Journals",
          myJournals: "My Journals",
          itineraryStats: "Statistics",
          followInfo: "Followers",
          followingInfo: "Following",
          diariesInfo: "Journals",
          editProfile: "Edit Personal Profile",
          fullNameLabel: "Full Name",
          locationLabel: "Location",
          bioLabel: "Bio description",
          placeholderName: "Enter full name...",
          placeholderLocation: "E.g. Hanoi, Vietnam",
          placeholderBio: "Write a short bio about yourself...",
        },
        landing: {
          heroTitle: "Record Journeys,",
          heroHighlight: "Share Experiences",
          heroSubtitle: "WanderLab is an authentic travel journal platform where you discover real experiences from the Vietnamese travel community.",
          startFree: "Start For Free",
          exploreBtn: "Explore Now",
          whyWanderLab: "Why WanderLab?",
          whySubtitle: "Vietnam's first travel journal platform with reliability verification",
          feat1Title: "Verified Journals",
          feat1Desc: "Every journal is verified by the community, ensuring realistic and trustworthy experiences.",
          feat2Title: "Explore Vietnam",
          feat2Desc: "Thousands of destinations from 63 provinces with detailed budgets and itineraries.",
          feat3Title: "AI Trip Planner",
          feat3Desc: "Smart AI assistant helps you plan the perfect trip in minutes.",
          readyToExplore: "Ready to explore?",
          readySubtitle: "Join a community of thousands of Vietnamese travelers sharing experiences daily.",
          createAccountFree: "Create Free Account",
          createStory: "Add story",
          trendingDestinations: "Trending Destinations",
          suggestedTravelers: "Featured Travelers",
          seeMoreTravelers: "View more travelers →",
          feedTitle: "Travel Journals",
          feedSubtitle: "Discover authentic experiences from the community",
          loadMoreFriends: "Connect With Friends",
          loadingDiaries: "Loading journals...",
          noDiaries: "No journals have been shared yet.",
        },
        explore: {
          title: "Explore Travel Journals",
          subtitle: "Discover authentic experiences from verified Vietnamese travelers",
          searchPlaceholder: "Search for destinations, provinces or experiences...",
          filters: "Filters",
          activeFilters: "active",
          clearAll: "Clear all",
          advancedFilters: "Advanced Filters",
          interests: "Interests",
          styles: "Travel Style",
          budget: "Budget Limit",
          duration: "Duration",
          from: "From",
          to: "To",
          under15tr: "Under 15m",
          over25tr: "Over 25m",
          all: "All",
          gridView: "Grid layout",
          mapView: "Map layout",
          mapPlaceholderTitle: "Map View Mode",
          mapPlaceholderDesc: "Interactive map coming soon! Switch to grid layout to view travel journals.",
          noResults: "No journals found",
          noResultsDesc: "Try adjusting your search query or filters",
          clearAllFilters: "Clear All Filters",
          showingDiaries: "Showing",
          journalsUnit: "journals",
          by: "by",
        },
        auth: {
          signIn: "Log In",
          signUp: "Sign Up",
          email: "Email Address",
          password: "Password",
          forgotPassword: "Forgot password?",
          dontHaveAccount: "Don't have an account?",
          haveAccount: "Already have an account?",
          fullName: "Full Name",
          confirmPassword: "Confirm Password",
        },
        createDiary: {
          title: "Create New Travel Journal",
          step1: "Basic Information",
          step2: "Daily Itinerary",
          step3: "Tips & Notes",
          step4: "Travel Photos",
          step5: "Privacy Settings",
          next: "Next",
          prev: "Back",
          finish: "Finish & Share",
          locationLabel: "Primary Destination",
          locationPlaceholder: "E.g. Phu Quoc",
          budgetLabel: "Estimated Total Cost",
          budgetPlaceholder: "E.g. 10,000,000₫",
          privacyPublic: "Public",
          privacyPublicDesc: "Anyone can view this travel journal",
          privacyFriends: "Friends Only",
          privacyFriendsDesc: "Only your followers can view",
          privacyPrivate: "Private",
          privacyPrivateDesc: "Only you can view this journal",
        },
        createItinerary: {
          title: "AI Trip Planner",
          subtitle: "Generate Personalized Itinerary",
          desc: "Answer 3 short questions – AI will create a perfect itinerary just for you",
          step1: "Destination",
          step2: "Group & Budget",
          step3: "Interests",
          step4: "Itinerary",
          selectDestDesc: "Select your dream destination",
          tripDuration: "Trip duration",
          question1: "Where do you want to go?",
          question2: "Who are you traveling with?",
          question3: "What is your budget?",
          question4: "What activities do you like most?",
          optimizeDesc: "Help AI optimize your itinerary",
          activitiesDesc: "Choose your favorite activities (multiple choice)",
          itinerarySummary: "Itinerary Summary",
          dailyItinerary: "Daily Itinerary",
          costEstimate: "Estimated Cost",
          totalEstimate: "Total estimate",
          communityJournals: "Real travel journals from the community",
          viewMoreJournals: "View more journals in Explore",
          share: "Share",
          viewSavedDashboard: "View saved itineraries in Dashboard",
          dayLabel: "Day",
          fitLabel: "Fit",
          trustScoreLabel: "Trust",
          backBtn: "Back",
          nextBtn: "Next",
          generateBtn: "Generate Itinerary",
          generating: "AI is creating itinerary...",
          resultTitle: "AI Generated Itinerary",
          saveItinerary: "Save Itinerary",
          saved: "Saved!",
          regenerate: "Regenerate",
        },
        diaryDetail: {
          trustScore: "Trust Score",
          verified: "Verified",
          travelerPhotos: "Traveler Photos",
          photosDesc: "authentic photos • Click to view full screen",
          saveToPlan: "Save to Plan",
          savedToPlan: "Saved",
          copyItinerary: "Copy Itinerary",
          share: "Share",
          aboutTrip: "About This Trip",
          dailyItinerary: "Daily Itinerary",
          budgetDetail: "Budget Details",
          tipsExperience: "Tips & Experience",
          budgetNotes: "💡 Budget Notes",
          budgetPct: "% of total budget",
          interactiveMap: "📍 Interactive Map",
          mapComingSoon: "Interactive route map coming soon",
          communityReviews: "Community Reviews",
          reviewsUnit: "reviews",
          commentsUnit: "comments",
          commentsTitle: "Comments",
          creator: "Travel Creator",
          follow: "Follow",
          tripInfo: "Trip Information",
          similarTrips: "Similar Trips",
          viewAllDiaries: "View All Journals →",
        },
        partner: {
          title: "For Travel Businesses",
          heroTitle: "Pricing Plans",
          heroDesc: "Join WanderLab's verified network and reach 50,000+ active travelers planning their next adventure.",
          viewPricing: "View Pricing",
          bookDemo: "Book a Demo",
          statPartners: "Partner Businesses",
          statTravelers: "Active Travelers",
          statROI: "Average ROI Increase",
          growthTitle: "Growth Analytics",
          growthDesc: "Track performance with real-time insights",
          trustTitle: "Trust Badge",
          trustDesc: "Verified partner status builds credibility",
          customersTitle: "Quality Customers",
          customersDesc: "Connect with ready-to-book travelers",
          globalTitle: "Global Reach",
          globalDesc: "Access international markets easily",
          whyTitle: "Why Partner With WanderLab?",
          whyDesc: "Everything you need to grow your travel business",
          pricingTitle: "Simple, Transparent Pricing",
          pricingDesc: "Choose the plan that fits your business needs",
          popular: "Most Popular",
          currentPlan: "Current Plan",
          upgrade: "Upgrade",
          benefit1Title: "50,000+ Active Travelers",
          benefit1Desc: "Connect with a verified community of travelers actively planning their trips",
          benefit2Title: "Targeted Reach",
          benefit2Desc: "Get discovered by travelers specifically interested in your destination and services",
          benefit3Title: "250% Average ROI",
          benefit3Desc: "Our partners see significant growth in bookings and brand visibility",
          benefit4Title: "Trust & Verification",
          benefit4Desc: "Benefit from a verification system that builds traveler trust",
          benefit5Title: "Real-time Analytics",
          benefit5Desc: "Track impressions, clicks, and conversions with detailed insights",
          benefit6Title: "Easy Integration",
          benefit6Desc: "Seamless setup with your existing booking system and website",
          freeDesc: "Free version - Currently using",
          freeFeat1: "AI Assistant: 5-10 requests/day",
          freeFeat2: "Upload Full HD content",
          freeFeat3: "Video storage limit",
          freeFeat4: "Create travel journals",
          freeFeat5: "Share with community",
          starterDesc: "Perfect for regular users",
          starterFeat1: "AI Assistant: 100 requests/month",
          starterFeat2: "2K video quality",
          starterFeat3: "Unlimited video storage",
          starterFeat4: "Basic analytics",
          starterFeat5: "Email support",
          starterFeat6: "Unlimited storage",
          proDesc: "For professional content creators",
          proFeat1: "AI Assistant: Unlimited",
          proFeat2: "4K ultra-sharp content",
          proFeat3: "Unlimited storage",
          proFeat4: "Profile personalization",
          proFeat5: "Advanced analytics & insights",
          proFeat6: "24/7 priority support",
          proFeat7: "Verification badge",
          proFeat8: "API Access",
        },
        friends: {
          title: "Friends",
          subtitle: "Connect and share travel experiences",
          searchPlaceholder: "Search for friends...",
          requests: "Friend requests",
          friendsList: "Friends",
          groups: "Travel groups",
          mutualFriends: "mutual friends",
          accept: "Accept",
          decline: "Decline",
          message: "Message",
          diaries: "journals",
          members: "members",
          posts: "posts",
          join: "Join",
          viewMore: "View more",
        }
      }
    };

    if (section) {
      return translations[lang]?.[section]?.[key] || translations['vi']?.[section]?.[key] || key;
    }
    return translations[lang]?.common?.[key] || translations['vi']?.common?.[key] || key;
  }
}));
