import { create } from 'zustand';

export type Language = 'vi' | 'en';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, section?: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: (localStorage.getItem('wanderlab-lang') as Language) || 'vi',
  setLanguage: (lang) => {
    localStorage.setItem('wanderlab-lang', lang);
    set({ language: lang });
  },
  t: (key, section) => {
    const lang = get().language;
    // Core translation dictionary for the entire website
    const translations: Record<Language, Record<string, any>> = {
      vi: {
        common: {
          home: "Trang Chủ",
          explore: "Khám Phá",
          friends: "Bạn Bè",
          createDiary: "Tạo Nhật Ký",
          createItinerary: "Tạo Lịch Trình",
          selectPlan: "Chọn Gói",
          dashboard: "Trang Cá Nhân",
          admin: "Quản Trị Viên",
          login: "Đăng Nhập",
          register: "Đăng Ký",
          logout: "Đăng Xuất",
          language: "Ngôn ngữ",
          loading: "Đang tải...",
          cancel: "Hủy",
          save: "Lưu thay đổi",
          shareMemory: "Chia sẻ kỷ niệm du lịch của bạn...",
          create: "Tạo",
          recentActivity: "Hoạt Động Gần Đây",
          totalLikes: "Tổng lượt thích",
          comments: "Bình luận",
          bookmarks: "Lượt lưu",
          quickActions: "Hành Động Nhanh",
          createJournal: "📝 Tạo Nhật Ký Mới",
          aiPlanner: "🗺️ Lập Kế Hoạch AI",
          searchExplore: "🔍 Khám Phá",
          edit: "Chỉnh sửa",
          changeCover: "Đổi ảnh bìa",
          location: "Địa điểm",
          travelStats: "Thống Kê Du Lịch",
          savedJournals: "Nhật Ký Đã Lưu",
          myJournals: "Nhật Ký",
          itineraryStats: "Thống Kê",
          followInfo: "người theo dõi",
          followingInfo: "đang theo dõi",
          diariesInfo: "nhật ký",
          editProfile: "Chỉnh Sửa Trang Cá Nhân",
          fullNameLabel: "Họ và tên",
          locationLabel: "Địa điểm",
          bioLabel: "Tiểu sử (Bio)",
          placeholderName: "Nhập họ và tên...",
          placeholderLocation: "Ví dụ: Hà Nội, Việt Nam",
          placeholderBio: "Giới thiệu ngắn về bản thân...",
        },
        landing: {
          heroTitle: "Ghi lại hành trình,",
          heroHighlight: "Chia sẻ trải nghiệm",
          heroSubtitle: "WanderLab là nền tảng nhật ký du lịch xác thực, nơi bạn khám phá trải nghiệm thật từ cộng đồng du lịch Việt Nam.",
          startFree: "Bắt Đầu Miễn Phí",
          exploreBtn: "Khám Phá",
          whyWanderLab: "Tại sao chọn WanderLab?",
          whySubtitle: "Nền tảng nhật ký du lịch đầu tiên tại Việt Nam với xác thực độ tin cậy",
          feat1Title: "Nhật Ký Xác Thực",
          feat1Desc: "Mọi nhật ký được xác minh bởi cộng đồng, đảm bảo trải nghiệm thực tế và đáng tin cậy.",
          feat2Title: "Khám Phá Việt Nam",
          feat2Desc: "Hàng ngàn điểm đến từ 63 tỉnh thành với ngân sách và lịch trình chi tiết.",
          feat3Title: "AI Lập Kế Hoạch",
          feat3Desc: "Trợ lý AI thông minh giúp bạn lập kế hoạch chuyến đi hoàn hảo trong vài phút.",
          readyToExplore: "Sẵn sàng khám phá?",
          readySubtitle: "Tham gia cộng đồng hàng nghìn du khách Việt Nam đang chia sẻ trải nghiệm mỗi ngày.",
          createAccountFree: "Tạo Tài Khoản Miễn Phí",
          createStory: "Tạo tin",
          trendingDestinations: "Điểm Đến Nổi Bật",
          suggestedTravelers: "Du Khách Nổi Bật",
          seeMoreTravelers: "Xem thêm du khách →",
          feedTitle: "Nhật Ký Du Lịch",
          feedSubtitle: "Khám phá trải nghiệm thật từ cộng đồng",
          loadMoreFriends: "Kết Nối Với Bạn Bè",
          loadingDiaries: "Đang tải nhật ký...",
          noDiaries: "Chưa có nhật ký nào được chia sẻ.",
        },
        explore: {
          title: "Khám Phá Nhật Ký Du Lịch",
          subtitle: "Khám phá trải nghiệm thực tế từ du khách Việt Nam đã được xác minh",
          searchPlaceholder: "Tìm kiếm điểm đến, tỉnh thành hoặc trải nghiệm...",
          filters: "Bộ Lọc",
          activeFilters: "đang dùng",
          clearAll: "Xóa tất cả",
          advancedFilters: "Bộ Lọc Nâng Cao",
          interests: "Sở Thích",
          styles: "Kiểu Du Lịch",
          budget: "Ngân Sách",
          duration: "Thời Gian",
          from: "Từ",
          to: "Đến",
          under15tr: "Dưới 15tr",
          over25tr: "Trên 25tr",
          all: "Tất cả",
          gridView: "Dạng lưới",
          mapView: "Dạng bản đồ",
          mapPlaceholderTitle: "Chế Độ Bản Đồ",
          mapPlaceholderDesc: "Bản đồ tương tác sẽ ra mắt sớm! Chuyển sang chế độ lưới để xem nhật ký.",
          noResults: "Không tìm thấy nhật ký",
          noResultsDesc: "Thử điều chỉnh tìm kiếm hoặc bộ lọc của bạn",
          clearAllFilters: "Xóa Tất Cả Bộ Lọc",
          showingDiaries: "Hiển thị",
          journalsUnit: "nhật ký",
          by: "bởi",
        },
        auth: {
          signIn: "Đăng Nhập",
          signUp: "Đăng Ký",
          email: "Địa chỉ Email",
          password: "Mật khẩu",
          forgotPassword: "Quên mật khẩu?",
          dontHaveAccount: "Chưa có tài khoản?",
          haveAccount: "Đã có tài khoản?",
          fullName: "Họ và tên",
          confirmPassword: "Xác nhận mật khẩu",
        },
        createDiary: {
          title: "Tạo Nhật Ký Chuyến Đi Mới",
          step1: "Thông Tin Cơ Bản",
          step2: "Lịch Trình",
          step3: "Mẹo & Lưu Ý",
          step4: "Ảnh Chuyến Đi",
          step5: "Quyền Riêng Tư",
          next: "Tiếp theo",
          prev: "Quay lại",
          finish: "Hoàn thành & Chia sẻ",
          locationLabel: "Địa điểm chính",
          locationPlaceholder: "Ví dụ: Phú Quốc",
          budgetLabel: "Tổng chi phí dự kiến",
          budgetPlaceholder: "Ví dụ: 10.000.000₫",
          privacyPublic: "Công khai",
          privacyPublicDesc: "Tất cả mọi người đều có thể xem nhật ký này",
          privacyFriends: "Bạn bè",
          privacyFriendsDesc: "Chỉ những người theo dõi bạn mới có thể xem",
          privacyPrivate: "Riêng tư",
          privacyPrivateDesc: "Chỉ mình bạn có thể xem nhật ký này",
        },
        createItinerary: {
          title: "AI Lập Kế Hoạch",
          subtitle: "Tạo Lịch Trình Cá Nhân Hóa",
          desc: "Trả lời 3 câu hỏi ngắn – AI sẽ tạo lịch trình hoàn hảo riêng cho bạn",
          step1: "Điểm đến",
          step2: "Nhóm & Ngân sách",
          step3: "Sở thích",
          step4: "Lịch trình",
          selectDestDesc: "Chọn điểm đến mơ ước của bạn",
          tripDuration: "Thời gian chuyến đi",
          question1: "Bạn muốn đi đâu?",
          question2: "Bạn đi cùng ai?",
          question3: "Mức ngân sách của bạn?",
          question4: "Bạn thích hoạt động gì nhất?",
          optimizeDesc: "Giúp AI tối ưu lịch trình cho bạn",
          activitiesDesc: "Chọn những hoạt động yêu thích (có thể chọn nhiều)",
          itinerarySummary: "Tóm tắt lịch trình",
          dailyItinerary: "Lịch trình từng ngày",
          costEstimate: "Ước tính chi phí",
          totalEstimate: "Tổng ước tính",
          communityJournals: "Nhật ký thực tế từ cộng đồng",
          viewMoreJournals: "Xem thêm nhật ký tại Khám phá",
          share: "Chia sẻ",
          viewSavedDashboard: "Xem lịch trình đã lưu trong Dashboard",
          dayLabel: "Ngày",
          fitLabel: "Phù hợp",
          trustScoreLabel: "Tin cậy",
          backBtn: "Quay lại",
          nextBtn: "Tiếp theo",
          generateBtn: "Tạo Lịch Trình",
          generating: "AI đang tạo lịch trình...",
          resultTitle: "Lịch trình được tạo bởi AI",
          saveItinerary: "Lưu lịch trình",
          saved: "Đã lưu!",
          regenerate: "Tạo lại",
        },
        diaryDetail: {
          trustScore: "Độ Tin Cậy",
          verified: "Đã Xác Minh",
          travelerPhotos: "Ảnh Từ Du Khách",
          photosDesc: "ảnh xác thực • Bấm để xem toàn màn hình",
          saveToPlan: "Lưu Vào Kế Hoạch",
          savedToPlan: "Đã Lưu",
          copyItinerary: "Sao Chép Lịch Trình",
          share: "Chia Sẻ",
          aboutTrip: "Về Chuyến Đi Này",
          dailyItinerary: "Lịch Trình Từng Ngày",
          budgetDetail: "Chi Tiết Ngân Sách",
          tipsExperience: "Mẹo Kinh Nghiệm",
          budgetNotes: "💡 Lưu Ý Ngân Sách",
          budgetPct: "% tổng ngân sách",
          interactiveMap: "📍 Bản Đồ Tương Tác",
          mapComingSoon: "Bản đồ lộ trình tương tác sẽ sớm ra mắt",
          communityReviews: "Đánh Giá Cộng Đồng",
          reviewsUnit: "đánh giá",
          commentsUnit: "bình luận",
          commentsTitle: "Bình Luận",
          creator: "Nhà Sáng Tạo Du Lịch",
          follow: "Theo Dõi",
          tripInfo: "Thông Tin Chuyến Đi",
          similarTrips: "Chuyến Đi Tương Tự",
          viewAllDiaries: "Xem Tất Cả Nhật Ký →",
        },
        friends: {
          title: "Bạn Bè",
          subtitle: "Quản lý danh sách bạn bè và nhóm du lịch của bạn",
          searchPlaceholder: "Tìm kiếm bạn bè, nhóm...",
        },
        partner: {
          pricingTitle: "Bảng Giá Đối Tác",
          currentPlan: "Gói hiện tại của bạn",
        }
      },
      en: {
        common: {
          home: "Home",
          explore: "Explore",
          friends: "Friends",
          createDiary: "Create Journal",
          createItinerary: "AI Itinerary",
          selectPlan: "Pricing Plans",
          dashboard: "Profile",
          admin: "Admin Panel",
          login: "Log In",
          register: "Sign Up",
          logout: "Log Out",
          language: "Language",
          loading: "Loading...",
          cancel: "Cancel",
          save: "Save Changes",
          shareMemory: "Share your travel memories...",
          create: "Create",
          recentActivity: "Recent Activity",
          totalLikes: "Total likes",
          comments: "Comments",
          bookmarks: "Saved posts",
          quickActions: "Quick Actions",
          createJournal: "📝 Create New Journal",
          aiPlanner: "🗺️ AI Plan Itinerary",
          searchExplore: "🔍 Search & Explore",
          edit: "Edit Profile",
          changeCover: "Change cover image",
          location: "Location",
          travelStats: "Travel Stats",
          savedJournals: "Saved Journals",
          myJournals: "My Journals",
          itineraryStats: "Statistics",
          followInfo: "Followers",
          followingInfo: "Following",
          diariesInfo: "Journals",
          editProfile: "Edit Personal Profile",
          fullNameLabel: "Full Name",
          locationLabel: "Location",
          bioLabel: "Bio description",
          placeholderName: "Enter full name...",
          placeholderLocation: "E.g. Hanoi, Vietnam",
          placeholderBio: "Write a short bio about yourself...",
        },
        landing: {
          heroTitle: "Record Journeys,",
          heroHighlight: "Share Experiences",
          heroSubtitle: "WanderLab is an authentic travel journal platform where you discover real experiences from the Vietnamese travel community.",
          startFree: "Start For Free",
          exploreBtn: "Explore Now",
          whyWanderLab: "Why WanderLab?",
          whySubtitle: "Vietnam's first travel journal platform with reliability verification",
          feat1Title: "Verified Journals",
          feat1Desc: "Every journal is verified by the community, ensuring realistic and trustworthy experiences.",
          feat2Title: "Explore Vietnam",
          feat2Desc: "Thousands of destinations from 63 provinces with detailed budgets and itineraries.",
          feat3Title: "AI Trip Planner",
          feat3Desc: "Smart AI assistant helps you plan the perfect trip in minutes.",
          readyToExplore: "Ready to explore?",
          readySubtitle: "Join a community of thousands of Vietnamese travelers sharing experiences daily.",
          createAccountFree: "Create Free Account",
          createStory: "Add story",
          trendingDestinations: "Trending Destinations",
          suggestedTravelers: "Featured Travelers",
          seeMoreTravelers: "View more travelers →",
          feedTitle: "Travel Journals",
          feedSubtitle: "Discover authentic experiences from the community",
          loadMoreFriends: "Connect With Friends",
          loadingDiaries: "Loading journals...",
          noDiaries: "No journals have been shared yet.",
        },
        explore: {
          title: "Explore Travel Journals",
          subtitle: "Discover authentic experiences from verified Vietnamese travelers",
          searchPlaceholder: "Search for destinations, provinces or experiences...",
          filters: "Filters",
          activeFilters: "active",
          clearAll: "Clear all",
          advancedFilters: "Advanced Filters",
          interests: "Interests",
          styles: "Travel Style",
          budget: "Budget Limit",
          duration: "Duration",
          from: "From",
          to: "To",
          under15tr: "Under 15m",
          over25tr: "Over 25m",
          all: "All",
          gridView: "Grid layout",
          mapView: "Map layout",
          mapPlaceholderTitle: "Map View Mode",
          mapPlaceholderDesc: "Interactive map coming soon! Switch to grid layout to view travel journals.",
          noResults: "No journals found",
          noResultsDesc: "Try adjusting your search query or filters",
          clearAllFilters: "Clear All Filters",
          showingDiaries: "Showing",
          journalsUnit: "journals",
          by: "by",
        },
        auth: {
          signIn: "Log In",
          signUp: "Sign Up",
          email: "Email Address",
          password: "Password",
          forgotPassword: "Forgot password?",
          dontHaveAccount: "Don't have an account?",
          haveAccount: "Already have an account?",
          fullName: "Full Name",
          confirmPassword: "Confirm Password",
        },
        createDiary: {
          title: "Create New Travel Journal",
          step1: "Basic Information",
          step2: "Daily Itinerary",
          step3: "Tips & Notes",
          step4: "Travel Photos",
          step5: "Privacy Settings",
          next: "Next",
          prev: "Back",
          finish: "Finish & Share",
          locationLabel: "Primary Destination",
          locationPlaceholder: "E.g. Phu Quoc",
          budgetLabel: "Estimated Total Cost",
          budgetPlaceholder: "E.g. 10,000,000₫",
          privacyPublic: "Public",
          privacyPublicDesc: "Anyone can view this travel journal",
          privacyFriends: "Friends Only",
          privacyFriendsDesc: "Only your followers can view",
          privacyPrivate: "Private",
          privacyPrivateDesc: "Only you can view this journal",
        },
        createItinerary: {
          title: "AI Trip Planner",
          subtitle: "Generate Personalized Itinerary",
          desc: "Answer 3 short questions – AI will create a perfect itinerary just for you",
          step1: "Destination",
          step2: "Group & Budget",
          step3: "Interests",
          step4: "Itinerary",
          selectDestDesc: "Select your dream destination",
          tripDuration: "Trip duration",
          question1: "Where do you want to go?",
          question2: "Who are you traveling with?",
          question3: "What is your budget?",
          question4: "What activities do you like most?",
          optimizeDesc: "Help AI optimize your itinerary",
          activitiesDesc: "Choose your favorite activities (multiple choice)",
          itinerarySummary: "Itinerary Summary",
          dailyItinerary: "Daily Itinerary",
          costEstimate: "Estimated Cost",
          totalEstimate: "Total estimate",
          communityJournals: "Real travel journals from the community",
          viewMoreJournals: "View more journals in Explore",
          share: "Share",
          viewSavedDashboard: "View saved itineraries in Dashboard",
          dayLabel: "Day",
          fitLabel: "Fit",
          trustScoreLabel: "Trust",
          backBtn: "Back",
          nextBtn: "Next",
          generateBtn: "Generate Itinerary",
          generating: "AI is creating itinerary...",
          resultTitle: "AI Generated Itinerary",
          saveItinerary: "Save Itinerary",
          saved: "Saved!",
          regenerate: "Regenerate",
        },
        diaryDetail: {
          trustScore: "Trust Score",
          verified: "Verified",
          travelerPhotos: "Traveler Photos",
          photosDesc: "authentic photos • Click to view full screen",
          saveToPlan: "Save to Plan",
          savedToPlan: "Saved",
          copyItinerary: "Copy Itinerary",
          share: "Share",
          aboutTrip: "About This Trip",
          dailyItinerary: "Daily Itinerary",
          budgetDetail: "Budget Details",
          tipsExperience: "Tips & Experience",
          budgetNotes: "💡 Budget Notes",
          budgetPct: "% of total budget",
          interactiveMap: "📍 Interactive Map",
          mapComingSoon: "Interactive route map coming soon",
          communityReviews: "Community Reviews",
          reviewsUnit: "reviews",
          commentsUnit: "comments",
          commentsTitle: "Comments",
          creator: "Travel Creator",
          follow: "Follow",
          tripInfo: "Trip Information",
          similarTrips: "Similar Trips",
          viewAllDiaries: "View All Journals →",
        },
        friends: {
          title: "Friends",
          subtitle: "Manage your friends list and travel groups",
          searchPlaceholder: "Search friends, groups...",
        },
        partner: {
          pricingTitle: "Partner Pricing",
          currentPlan: "Your current plan",
        }
      }
    };

    if (section) {
      return translations[lang]?.[section]?.[key] || translations['vi']?.[section]?.[key] || key;
    }
    return translations[lang]?.common?.[key] || translations['vi']?.common?.[key] || key;
  }
}));
